# Generated by Django 5.0.2 on 2025-06-21 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('text_comments', models.TextField(max_length=240, verbose_name='текст коментаря')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.post', verbose_name='публікації')),
            ],
            options={
                'verbose_name': 'коментар',
                'verbose_name_plural': 'коментарi',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.post', verbose_name='публікація')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='користувач')),
            ],
            options={
                'verbose_name': 'лайк',
                'verbose_name_plural': 'лайки',
                'unique_together': {('user', 'post')},
            },
        ),
    ]
