# Generated by Django 5.0.2 on 2026-02-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, upload_to='image/%Y', verbose_name='зображеня'),
        ),
    ]
