# Generated by Django 5.0.2 on 2025-08-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_alter_comments_text_comments_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=500, verbose_name='текст поста'),
        ),
    ]
