# Generated by Django 5.0.2 on 2025-06-21 18:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OwnUserPost',
            fields=[
                ('title', models.CharField(max_length=70, verbose_name='заголовок поста')),
                ('description', models.TextField(verbose_name='текст поста')),
                ('author', models.CharField(max_length=60, verbose_name='імя автора')),
                ('img', models.ImageField(blank=True, upload_to='image/', verbose_name='зображеня')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='дата публікації')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='заголовок поста')),
                ('description', models.TextField(verbose_name='текст поста')),
                ('author', models.CharField(max_length=60, verbose_name='імя автора')),
                ('img', models.ImageField(blank=True, upload_to='image/%Y', verbose_name='зображеня')),
                ('date', models.DateField(verbose_name='дата публікації')),
            ],
            options={
                'verbose_name': 'Запис',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, verbose_name='ip_address')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='публікація')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('text_comments', models.TextField(max_length=240, verbose_name='текст коментаря')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='публікації')),
            ],
            options={
                'verbose_name': 'коментар',
                'verbose_name_plural': 'коментарi',
            },
        ),
    ]
