# Generated by Django 5.0.2 on 2024-10-19 15:13

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_ownuserpost_date_alter_ownuserpost_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownuserpost',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 10, 19, 15, 13, 28, 363840, tzinfo=datetime.timezone.utc), verbose_name='дата публікації'),
        ),
        migrations.AlterField(
            model_name='ownuserpost',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1f8d796c-3b1d-4363-b5f8-a586bcee53b3'), primary_key=True, serialize=False),
        ),
    ]
