# Generated by Django 5.0.2 on 2024-10-19 15:18

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_ownuserpost_date_alter_ownuserpost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownuserpost',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 10, 19, 15, 18, 27, 691960, tzinfo=datetime.timezone.utc), verbose_name='дата публікації'),
        ),
        migrations.AlterField(
            model_name='ownuserpost',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
