# Generated by Django 5.0.2 on 2024-10-19 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_ownuserpost_date_alter_ownuserpost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownuserpost',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 10, 19, 15, 19, 52, 587609, tzinfo=datetime.timezone.utc), verbose_name='дата публікації'),
        ),
    ]
