# Generated by Django 5.0.2 on 2025-02-14 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_rest', '0002_post_delete_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
    ]
